export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SET_BOOKS = 'SET_BOOKS';
export const ADD_BOOK = 'ADD_BOOK';
export const BOOK_FETCHED = 'BOOK_FETCHED';
export const BOOK_UPDATED = 'BOOK_UPDATED';
export const BOOK_DELETED = 'BOOK_DELETED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';